# spring.application.name=ctask
# spring.datasource.url=jdbc:postgresql://localhost:5432/ctask
# spring.datasource.username=postgres
# spring.datasource.password=1234

spring.application.name=${DB_NAME}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
#Para crear las tablas solas
spring.jpa.hibernate.ddl-auto=update